spring:
  application:
    name:
      SafeShelf
  mvc:
    async:
      request-timeout: -1
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/safeshelf
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 50000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      uri: mongodb://localhost:27017/dishes


server:
  port:
    8080

clients:
  generator-dishes:
    base-url: http://localhost:8001


springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  key: iZRaS9EQ0Gl2KdX8MQcy8Wy69x8CnvZneoZ2bVxd5291tQGa0jGRkWgFs99zZBjJ9ENM4k1XOYKw2bS3q1lLkjQ5MpGqAtD9ofhSGD6ytSnERSMyG8G
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

