spring:
  application:
    name:
      SafeShelf
  datasource:
    url: jdbc:postgresql://localhost:5432/safeshelf
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port:
    8000

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html