spring:
  application:
    name:
      SafeShelf
  datasource:
    url: jdbc:postgresql://localhost:5432/safeshelf
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none

server:
  port:
    8000

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html