spring:
  application:
    name:
      SafeShelf
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/safeshelf
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none

server:
  port:
    8000

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  key: iZRaS9EQ0Gl2KdX8MQcy8Wy69x8CnvZneoZ2bVxd5291tQGa0jGRkWgFs99zZBjJ9ENM4k1XOYKw2bS3q1lLkjQ5MpGqAtD9ofhSGD6ytSnERSMyG8G
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

